export default function TransparentFoundation() {
  return (
    <div className="relative h-screen w-screen overflow-hidden bg-[#0c0f1a] font-body text-white">
      <div className="pointer-events-none absolute inset-0 opacity-50" style={{ backgroundImage: 'linear-gradient(rgba(255,255,255,.035) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.035) 1px, transparent 1px)', backgroundSize: '4vw 4vw' }} />
      <div className="absolute -right-[10vw] -top-[18vh] h-[50vw] w-[50vw] rounded-full bg-[#4f7fff]/[.07] blur-[8vw]" />
      <div className="absolute -bottom-[28vh] -left-[12vw] h-[55vw] w-[55vw] rounded-full bg-[#7c6bf0]/[.06] blur-[10vw]" />
      <div className="absolute left-[5vw] top-[5vh] flex items-center gap-[1vw]"><div className="h-[2vw] w-[2vw] rounded-[.4vw] bg-[#4f7fff]" /><span className="text-[1.2vw] font-bold">primevora<span className="text-[#4f7fff]">.</span></span></div>
      <div className="absolute right-[5vw] top-[5vh] text-[1vw] text-white/45">06 / 06</div>
      <div className="relative z-10 mx-auto flex h-full w-[82vw] items-center justify-between gap-[6vw]">
        <div className="w-[49%]"><div className="mb-[2vh] w-fit rounded-[2vw] border border-[#4f7fff]/40 bg-[#4f7fff]/15 px-[1vw] py-[.55vh] text-[.9vw] font-semibold uppercase tracking-[.1em] text-[#8eacff]">Current foundation</div><h2 className="font-display text-[4vw] font-extrabold leading-[1.08] tracking-[-.05em]">A transparent foundation for what comes next</h2><div className="mt-[4vh] flex flex-col gap-[1.6vh] text-[1.05vw] leading-[1.35] text-white/72"><div className="flex gap-[.8vw]"><span className="text-[#4f7fff]">01</span><span>Current build uses clearly labeled demo transaction data during development</span></div><div className="flex gap-[.8vw]"><span className="text-[#4f7fff]">02</span><span>Live market pricing is fetched from CoinGecko with no hard-coded fallback</span></div><div className="flex gap-[.8vw]"><span className="text-[#4f7fff]">03</span><span>Next production priorities: durable storage, strict admin authorization, and automated regression tests</span></div><div className="flex gap-[.8vw]"><span className="text-[#4f7fff]">04</span><span>Primevora is designed to make every important action legible</span></div></div></div>
        <div className="relative flex-1">
          <div className="rounded-[1vw] border border-white/10 bg-[#131726] p-[1.8vw] shadow-2xl"><div className="flex items-center justify-between border-b border-white/[.07] pb-[1.5vh]"><span className="text-[.8vw] uppercase tracking-[.12em] text-white/40">Foundation map</span><span className="text-[.8vw] text-[#8eacff]">in view</span></div><div className="mt-[2.5vh] grid grid-cols-2 gap-[1vw]"><div className="rounded-[.7vw] bg-[#4f7fff]/10 p-[1.1vw]"><p className="text-[.75vw] uppercase text-white/42">Market data</p><p className="mt-[1.2vh] text-[1.1vw] font-semibold text-[#9db5ff]">Live context</p><div className="mt-[1.5vh] h-[.35vw] rounded-full bg-[#4f7fff]/60" /></div><div className="rounded-[.7vw] bg-[#7c6bf0]/10 p-[1.1vw]"><p className="text-[.75vw] uppercase text-white/42">Demo mode</p><p className="mt-[1.2vh] text-[1.1vw] font-semibold text-[#b5acff]">Clearly labeled</p><div className="mt-[1.5vh] h-[.35vw] rounded-full bg-[#7c6bf0]/60" /></div></div><div className="mt-[1.8vh] rounded-[.7vw] border border-white/[.07] bg-white/[.025] p-[1.1vw]"><div className="flex items-center justify-between text-[.8vw] text-white/45"><span>Next production priorities</span><span>03</span></div><div className="mt-[1.6vh] flex gap-[.7vw]"><span className="rounded-[.35vw] bg-white/[.06] px-[.7vw] py-[.6vh] text-[.75vw] text-white/65">Storage</span><span className="rounded-[.35vw] bg-white/[.06] px-[.7vw] py-[.6vh] text-[.75vw] text-white/65">Authorization</span><span className="rounded-[.35vw] bg-white/[.06] px-[.7vw] py-[.6vh] text-[.75vw] text-white/65">Tests</span></div></div></div>
          <div className="absolute -bottom-[3vh] -right-[2vw] rounded-[.8vw] border border-[#4f7fff]/30 bg-[#101626] px-[1.2vw] py-[1.2vh] text-[.9vw] text-white/75 shadow-xl"><span className="mr-[.5vw] text-[#4f7fff]">✓</span> Every important action legible</div>
        </div>
      </div>
      <div className="absolute bottom-[5vh] left-[5vw] text-[.9vw] tracking-[.05em] text-white/35">PRIMEVORA / NEXT FOUNDATION</div>
    </div>
  );
}