export default function TrustFlow() {
  return (
    <div className="relative h-screen w-screen overflow-hidden bg-[#0c0f1a] font-body text-white">
      <div className="pointer-events-none absolute inset-0 opacity-45" style={{ backgroundImage: 'linear-gradient(rgba(255,255,255,.035) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.035) 1px, transparent 1px)', backgroundSize: '4vw 4vw' }} />
      <div className="absolute -bottom-[18vh] right-[4vw] h-[45vw] w-[45vw] rounded-full bg-[#4f7fff]/[.06] blur-[10vw]" />
      <div className="absolute left-[5vw] top-[5vh] flex items-center gap-[1vw]"><div className="h-[2vw] w-[2vw] rounded-[.4vw] bg-[#4f7fff]" /><span className="text-[1.2vw] font-bold">primevora<span className="text-[#4f7fff]">.</span></span></div>
      <div className="absolute right-[5vw] top-[5vh] text-[1vw] text-white/45">04 / 06</div>
      <div className="relative z-10 mx-auto flex h-full w-[82vw] items-center gap-[6vw]">
        <div className="w-[43%]"><div className="mb-[2vh] w-fit rounded-[2vw] border border-[#4f7fff]/40 bg-[#4f7fff]/15 px-[1vw] py-[.55vh] text-[.9vw] font-semibold uppercase tracking-[.1em] text-[#8eacff]">Safety by design</div><h2 className="font-display text-[4vw] font-extrabold leading-[1.08] tracking-[-.05em]">Trust is built into the flow</h2><div className="mt-[4vh] flex flex-col gap-[1.6vh] text-[1.05vw] leading-[1.35] text-white/72"><div className="flex gap-[.8vw]"><span className="text-[#7c6bf0]">01</span><span>KYC submission with Pending, Approved, and Rejected states</span></div><div className="flex gap-[.8vw]"><span className="text-[#7c6bf0]">02</span><span>Withdrawals remain locked until KYC is approved</span></div><div className="flex gap-[.8vw]"><span className="text-[#7c6bf0]">03</span><span>Three-step withdrawal review: amount, address, final amount</span></div><div className="flex gap-[.8vw]"><span className="text-[#7c6bf0]">04</span><span>Fee visibility before confirmation</span></div><div className="flex gap-[.8vw]"><span className="text-[#7c6bf0]">05</span><span>Clear warning: never share private keys, seed phrases, or wallet passwords</span></div></div></div>
        <div className="flex-1">
          <div className="rounded-[1vw] border border-white/10 bg-[#131726] p-[2vw] shadow-2xl"><p className="text-[.8vw] uppercase tracking-[.12em] text-white/42">Withdrawal review</p><div className="mt-[3vh] grid grid-cols-3 gap-[.8vw]"><div className="rounded-[.7vw] border border-[#4f7fff]/50 bg-[#4f7fff]/10 p-[1vw]"><span className="text-[.8vw] text-[#9db5ff]">01</span><p className="mt-[1.5vh] text-[.95vw] font-semibold">Amount</p></div><div className="rounded-[.7vw] border border-[#7c6bf0]/50 bg-[#7c6bf0]/10 p-[1vw]"><span className="text-[.8vw] text-[#b5acff]">02</span><p className="mt-[1.5vh] text-[.95vw] font-semibold">Address</p></div><div className="rounded-[.7vw] border border-white/10 bg-white/[.03] p-[1vw]"><span className="text-[.8vw] text-white/42">03</span><p className="mt-[1.5vh] text-[.95vw] font-semibold text-white/70">Final amount</p></div></div><div className="mt-[3vh] rounded-[.7vw] bg-white/[.04] p-[1.2vw]"><div className="flex justify-between text-[.9vw] text-white/55"><span>Withdrawal amount</span><span className="font-mono text-white">400.00 USDT</span></div><div className="mt-[1.4vh] flex justify-between text-[.9vw] text-white/55"><span>Network fee</span><span className="font-mono text-[#b5acff]">− 4.00 USDT</span></div><div className="mt-[1.4vh] flex justify-between border-t border-white/10 pt-[1.4vh] text-[1.05vw] font-semibold"><span>You receive</span><span className="font-mono text-[#8eacff]">396.00 USDT</span></div></div><div className="mt-[2vh] flex items-center gap-[.7vw] rounded-[.6vw] border border-[#7c6bf0]/30 bg-[#7c6bf0]/10 p-[1vw] text-[.85vw] text-white/65"><span className="text-[#b5acff]">✓</span> Address confirmation required before submission</div></div>
        </div>
      </div>
      <div className="absolute bottom-[5vh] left-[5vw] text-[.9vw] tracking-[.05em] text-white/35">PRIMEVORA / SAFETY BY DESIGN</div>
    </div>
  );
}